### ISSUE TITLE
SPI communication with RPI

### ISSUE THREAD

**Issue by Oishe** [neurotechuoft/Biosignals-Board#13]
[ADS1299-RPI Project](https://github.com/shanjit/ese519-project-spring2015)

**Comment by a1bertle** [comment]
This milestone has been changed to interfacing a Raspberry Pi with an Arduino over SPI. This has been completed with the code [here](https://github.com/neurotechuoft/Biosignals-Board/tree/master/code/software/arduino/ads1299_arduino_emulator/ads1299_arduino_emulator.ino)
